In [5]:
import plotly.express as px
import plotly.graph_objects as go
import pandas
from pathlib import Path
import os

mtdnrc_dir = Path(r'C:\Users\CNB968\OneDrive - MT\GitHub\MTDNRCdata')
os.chdir(mtdnrc_dir)

from MTDNRCdata.stage import GetSite
from MTDNRCdata.stage import get_location_parameters

In [6]:
get_location_parameters('41O 03000')

,attributes.Parameter,attributes.ParameterLabel,attributes.ComputationPeriod,attributes.UnitOfMeasure,attributes.SensorCode
0,TW,Water Temp,Daily,degC,Water Temp.Daily Average@41O 03000
1,HG,Stage,Unknown,ft,Stage.working@41O 03000
2,HG,Stage,Daily,ft,Stage.Daily Average@41O 03000
3,QR,Discharge,Unknown,ft^3/s,Discharge.discharge@41O 03000
4,TW,Water Temp,Unknown,degC,Water Temp.water temp@41O 03000
5,QR,Discharge,Daily,ft^3/s,Discharge.Daily Average@41O 03000

In [2]:
sphill = GetSite('41O 03000', timestep='daily', dataset='QR', start='2024-01-01', end='2024-11-12')

In [3]:
sphill.site_info

,LocationCode,LocationName,LocationType,Longitude,Latitude,Elevation,ElevationUnits,Description,AvailableDatasets,CountyName,BasinName,HUC8Code
0,41O 03000,Teton River above Springhill,Hydrology Station,-112.301063,47.871539,4058.0,ft,Real-time Bubbler System,"TW,HG,HG,QR,TW,QR",Teton,Upper Missouri Basin,10030205

In [3]:
sphill.data.drop_duplicates(subset='Date', inplace=True)

In [32]:
sphill.data['RecordedValue'].iloc[-1]

8.78363179

In [43]:
fig = px.line(sphill.data, x='Date', y='RecordedValue', 
              color='SiteID',
              template='simple_white')
fig.add_traces(go.Scatter(x=sphill.data[sphill.data['Date'] == '2024-11-11'].Date, y=[sphill.data['RecordedValue'].iloc[-1]], 
                          mode='markers', 
                          name='Today',
                          marker=dict(
                              size=10,
                              color='red'
                          )))
fig.update_layout(width=800, height=600)
fig.update_layout(yaxis=dict(title=dict(text='Discharge (cfs)', font=dict(size=18))))
fig.update_xaxes(range=['2024-01-01', '2024-12-31'])
fig.show()